name: 'markdown-links-action'
description: 'Markdown Link Checker, automates the process of validating links in Markdown files within a GitHub repository. It ensures that all hyperlinks in your documentation are functional and up-to-date, helping maintain the integrity and reliability of your project documentation.'
author: 'Roman Dutchak'

branding:
  icon: 'heart'
  color: 'red'

inputs:
  config-file:
    description: 'Specify path to a markdown-link-check JSON configuration file.'
    required: true
    default: '.markdown-links.json'
  folder-path:
    description: 'Specify path to a custom folder where your markdown files are located.'
    required: true
    default: '.'
  max-depth:
    description: 'Specify a max-depth of directories you want to search for markdown files.'
    required: true
    default: '-1'
  check-modified-files-only:
    description: 'Use yes to only check for modified markdown files instead of checking all markdown files.'
    required: true
    default: 'no'
  base-branch:
    description: 'Use this to specify the base branch against which the action finds the modififed files.'
    required: true
    default: 'main'
  file-extension:
    description: 'Use this to specify the file extension of Markdown files.'
    required: true
    default: '.md'
  file-path:
    description: 'Specify additional files you want to check'
    required: true
    default: ''
  create-issue:
    description: 'Create issue with broken links'
    required: true
    default: 'no'
  gh-assignees:
    description: 'Assignees for the issue'
    required: false
    default: ''
  gh-labels:
    description: 'Labels for the issue'
    required: false
    default: ''
  repo-token:
    description: 'GitHub token'
    required: true
    default: ''
  repository:
    description: 'GitHub repository (owner/repo)'
    required: true
    default: ''

outputs:
  dead-links:
    description: 'List of broken links'

runs:
  using: node20
  main: dist/index.js
